import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Container, Typography } from "@mui/material";
import Carousel from "@/components/carousel";
import { ImageCarousel } from "@/components/imageCarousel";
import { IceBear } from "@/components/icebear";
import { HeroImage } from "@/components/HeroImage";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [change, setChange] = useState(false);
  const [error, setError] = useState("");

  const answerHandler = (answer) => {
    if (answer.toLowerCase() === "to live for the hope of it all") {
      setChange(true);
    } else {
      setError("You seems to be an Imposter !");
    }
  };
  return (
    <>
      <Head>
        <title>The Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Box sx={{ display: { xs: "none", md: "contents" } }}>
          <IceBear fetchAnswer={answerHandler} change={change} error={error} />

          {change && (
            <>
              <HeroImage />
              <Box sx={{ mx: -1 }}>
                <Container maxWidth="xl">
                  <Box sx={{ mx: -3 }}>
                    <ImageCarousel />
                  </Box>
                </Container>
              </Box>
              <Container maxWidth="xl">
                <Carousel />
              </Container>
              <Container
                maxWidth="xl"
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  height: "100vh",
                  overflowX: "hidden",
                }}
              >
                <Typography sx={{ color: "#4F200D", fontSize: "20px" }}>
                  52697961 426973686E6F69
                </Typography>
                <Typography sx={{ color: "#4F200D", fontSize: "20px" }}>
                  XOTWOD
                </Typography>
              </Container>{" "}
            </>
          )}
        </Box>
        <Box
          sx={{
            display: { xs: "flex", md: "none" },
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            height: "100vh",
          }}
        >
          <Typography sx={{ color: "#4F200D", fontSize: "20px" }}>
            For Best Experience open in MAC/PC
          </Typography>
        </Box>
      </main>
    </>
  );
}
